// CacheDetail.swift — what a cache is actually made of.
//
// "Adobe's cache is 99 GB" is a number without an explanation, and an unexplained number is
// not something a person can act on. The real answer for this machine was that 92.5 GB of
// that 99 GB is one thing: After Effects' disk cache, 241,947 .aecache files. That is a
// decision you can make. "Adobe: 99 GB" is not.
import Foundation

struct CacheBreakdown: Sendable {
    struct Part: Identifiable, Sendable {
        var id: String { path }
        var name: String
        var path: String
        var bytes: Int64
        var files: Int
    }
    var parts: [Part] = []
    /// The dominant file extension, when one clearly dominates.
    var mainExtension: String? = nil
    var totalFiles: Int = 0
    var newest: Date? = nil
}

enum CacheDetail {
    /// Immediate children by size, plus the file mix. Bounded on purpose: it walks to find
    /// sizes but samples extensions, because a quarter of a million files does not need to
    /// be classified individually to say "these are .aecache".
    static func inspect(_ path: String, limit: Int = 6) -> CacheBreakdown {
        let root = (path as NSString).expandingTildeInPath
        let fm = FileManager.default
        var out = CacheBreakdown()

        let names = ((try? fm.contentsOfDirectory(atPath: root)) ?? []).filter { !$0.hasPrefix(".") }
        var parts: [CacheBreakdown.Part] = []
        for n in names {
            let p = (root as NSString).appendingPathComponent(n)
            let m = measure(p)
            guard m.sizeMb > 0 || m.fileCount > 0 else { continue }
            parts.append(.init(name: n, path: p,
                               bytes: Int64(m.sizeMb * 1_048_576), files: m.fileCount))
            out.totalFiles += m.fileCount
            if let t = m.newestMtime {
                let d = Date(timeIntervalSince1970: Double(t) / 1000)
                if out.newest == nil || d > out.newest! { out.newest = d }
            }
        }
        out.parts = parts.sorted { $0.bytes > $1.bytes }.prefix(limit).map { $0 }

        // sample extensions from the largest part rather than the whole tree
        if let biggest = out.parts.first {
            var counts: [String: Int] = [:]
            var seen = 0
            if let e = fm.enumerator(atPath: biggest.path) {
                while let f = e.nextObject() as? String, seen < 2000 {
                    let ext = (f as NSString).pathExtension.lowercased()
                    if !ext.isEmpty { counts[ext, default: 0] += 1; seen += 1 }
                }
            }
            if let top = counts.max(by: { $0.value < $1.value }),
               Double(top.value) / Double(max(seen, 1)) > 0.6 {
                out.mainExtension = top.key
            }
        }
        return out
    }

    /// Why this cache exists and what refills it. Written per family, because "cache" tells
    /// someone nothing about whether losing it costs a second or an afternoon.
    static func origin(forID id: String) -> String? {
        switch id {
        case let x where x.hasPrefix("gen-adobe"):
            return "Mostly After Effects' disk cache: rendered frames kept so scrubbing a comp is instant. It refills as you work and is capped in After Effects under Preferences, Media and Disk Cache."
        case "resolve-cache":
            return "Resolve's render cache: frames rendered ahead so playback is smooth. It regrows as you play back a timeline, and Resolve can clear it under Playback, Delete Render Cache."
        case "premiere-media":
            return "Conformed audio and indexed video Premiere builds the first time it sees a clip, so scrubbing does not re-decode. Rebuilt on next open, which makes that first playback slower."
        case "premiere-peaks":
            return "Audio waveform drawings. Small, and redrawn almost instantly."
        case "gen-xcode", "gen-deriveddata":
            return "Compiled intermediates from builds. Regenerated by the next build, at the cost of one slow build."
        case let x where x.hasPrefix("lr-"):
            return "Lightroom previews: rendered JPEGs so the library grid scrolls without touching the raw files. Rebuilt on demand, slowly for a large catalogue."
        case let x where x.hasPrefix("gen-"):
            return "Working files the app rebuilds by itself when it next needs them."
        default: return nil
        }
    }
}
